# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 992a49f5e2493367c5cf5d0e73c9c642cc8c0ff572e8ec028be297ac683e62a6552365c70282d9d82023982a3614c51858f5dca96a3f655cda6554daab3b6e37

test:
  secret_key_base: d3e7a16947d5f5db38562e8b3cd224073ec68d16c18f28ba65006b9daf36fe12857fd7a59190bea70bb6410fa0fb93817f71b03eb4521742f798add6e2265cbc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
